### ISSUE TITLE
能否增加导航栏颜色设置，这样可以设置成与弹窗相同颜色，更协调嘞。哈哈

### ISSUE THREAD

**Issue by iLucasLiu** [javakam/PickerView#11]

**Comment by iLucasLiu** [comment]
![Screenshot_20231017_174123](https://github.com/javakam/PickerView/assets/3734375/e94350bf-3060-48c6-aa9f-86d4d4643fb0)

**Comment by javakam** [comment]
原生的Dialog捣鼓过没弄出来, 最后用的Activity实现的Dialog ...   https://github.com/javakam/DialogManager/issues/4
