### ISSUE TITLE
原库有个小bug。

### ISSUE THREAD

**Issue by wuzhongyuan** [javakam/PickerView#4]
![image](https://github.com/javakam/PickerView/assets/14008924/e023e849-816f-4011-b003-890d86c4e215)

**Comment by javakam** [comment]
具体啥问题...

**Comment by wuzhongyuan** [comment]
> 具体啥问题...

是我的代码执行到这行角标越界了，就是opt1Select不能大于mOptions2Items的size，但是实际是可能会出现大于的情况，后来我调整了一下我的代码，初始化的时候不让opt1Select大于mOptions2Item的size。
