### ISSUE TITLE
您好，有没有去掉3D滚轮效果的接口呢？

### ISSUE THREAD

**Issue by iLucasLiu** [javakam/PickerView#5]

**Comment by javakam** [comment]
刚更新了1.7.0 , 用新增的`setOuterTextScale(false)`关闭非中间字体3D效果

![image](https://github.com/javakam/PickerView/assets/15343661/3c0af9e0-eba7-4407-8dc3-beb9622c2ca7)

![image](https://github.com/javakam/PickerView/assets/15343661/a1cef98e-1991-487e-8dc5-08c683a493aa)

**Comment by iLucasLiu** [comment]
我擦，帅哥很棒，已更新到新版啦😍还有个Ui方面的问题，默认对话框能否渗透导航栏，这样看上去更统一协调。发自我的 iPhone在 2023年9月7日，17:43，javakam ***@***.***> 写道：﻿
刚更新了1.7.0 , 用新增的setOuterTextScale(false)关闭非中间字体3D效果

**Comment by iLucasLiu** [comment]
还有个问题：isCenterLabel设置后，文字显示的距离调整下会更好些。现在日期距离label太远了。🤪发自我的 iPhone在 2023年9月7日，17:43，javakam ***@***.***> 写道：﻿
刚更新了1.7.0 , 用新增的setOuterTextScale(false)关闭非中间字体3D效果

**Comment by javakam** [comment]
v1.8.0 修复原版`isCenterLabel=true`显示异常问题并增加`setCenterLabelSpacing(float)`控制文本和"年月日"等单位的间距
