### ISSUE TITLE
急，有个紧急的bug，OptionsPickerBuilder创建的对话框的边距无法取消

### ISSUE THREAD

**Issue by iLucasLiu** [javakam/PickerView#9]
![Screenshot_20231011_113759](https://github.com/javakam/PickerView/assets/3734375/098745c2-6f3f-46d4-b18c-fe60a53d3c29)
您好，之前使用TimePickerBuilder可以正常去掉对话框距离屏幕左右的间距，但是同样的方法使用OptionsPickerBuilder却无法取消对话框距离屏幕两侧的边距。

**Comment by javakam** [comment]
贴下代码, 看上去像是用成了  .isDialog(true)

**Comment by iLucasLiu** [comment]
![ME1697079106300](https://github.com/javakam/PickerView/assets/3734375/d7b7a0bb-391d-4f56-9aa0-385f238f77db)
是使用Dialog样式，但已经设置的距离屏幕两侧距离为0了，实际无效，还是有间距。
但TimePickerBuilder使用dialog样式去掉边距就没有问题，就像前几个issue图片中的时间选择对话框。

**Comment by iLucasLiu** [comment]
我们明天提测，看看帅哥能抽空看下这个问题么。

**Comment by javakam** [comment]
改成false就行了

**Comment by iLucasLiu** [comment]
> 改成false就行了

ok解决了,按您说的可以啦，我以为选对话框样式所以isDialog设为true了。这块和TimePickerBuilder还有点区别。

**Comment by iLucasLiu** [comment]
ok解决了,按您说的可以啦，我以为选对话框样式所以isDialog设为true了。这块和TimePickerBuilder还有点区别。
